#
# GitLab example CI/CD script
# See https://docs.gitlab.com/ee/ci/yaml/README.html
#
# Secure Variables like $DB_PASSWORD can added by going to your
# project’s Settings ➔ CI / CD ➔ Variables on the GitLab website.
#
# image: node:latest
stages:
    - test
    - production
#
# Global variables
#
variables:
    # Configure mysql environment variables (https://hub.docker.com/_/mysql/)
    MYSQL_DATABASE: my_mysql_database
    MYSQL_ROOT_PASSWORD: some_secret_password
    # DOCKER_HOST: tcp://docker:2375/
    # DOCKER_DRIVER: overlay2
#
# Testing nodejes backend
# Our server uses a MySql database, so to run our testcases we also need a database.
# We do NOT use the online production database, but spawn an independent test-db on Gitlab.
# To do so, we have to install it into the container where we run our testcases.
#
testing:
    stage: test
    image: node:latest
    services:
        - mysql:5.6
    variables:
        NODE_ENV: development
        DB_USER: root
        DB_DATABASE: ${MYSQL_DATABASE}
        DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        DB_HOST: mysql
    before_script:
        # # Install the database into the node:latest container
        # - apt-get update
        # - apt-get -y install mysql-client
        # # Create our database by running the database.sql script
        # - mysql --host=mysql --user="${DB_USER}" --password="${DB_PASSWORD}" ${DB_DATABASE} < movies.sql
        # - mysqlshow --host=mysql --user="${DB_USER}" --password="${DB_PASSWORD}" ${DB_DATABASE}
        # # Install the node packages that our server needs.
        - npm install --no-optional
    script:
        - echo "npm run test not ready yet"
        # - echo "SONAR_LOGIN_KEY = $SONAR_LOGIN_KEY"
        # - echo "SONAR_PROJECT_KEY = $SONAR_PROJECT_KEY"
        # - npm run sonar
#
# Deploy to Heroku
# DPL is a deploy tool made for continuous deployment that’s developed and used
# by Travis CI, but can also be used with GitLab CI.
# https://docs.gitlab.com/ee/ci/examples/deployment/#using-dpl-with-docker
#
production:
    type: deploy
    stage: production
    image: ruby:latest
    script:
        # Get your key at https://dashboard.heroku.com/account
        # and add it to your project environment variables at GitLab.
        - echo "Heroku api key = $HEROKU_API_KEY"
        # The name of your app at Heroku. See https://dashboard.heroku.com/apps.
        - echo "Heroku appname = $HEROKU_APP_NAME"
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
        - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
    only:
        - main
